register_rest/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('repreStudy/', include('repreStudy.urls')),
    path('', views.index , name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

repreStudy/urls.py
from django.urls import path, include

urlpatterns = [
    path('login/', include('repreStudy.login_urls')),
    path('representante/', include('repreStudy.representante_urls')),
    path('alumno/', include('repreStudy.alumno_urls')),
]

repreStudy/models.py
from django.db import models
from django.contrib.auth.models import User


# creando DB de representantes
class Representante(models.Model):
    cedula = models.CharField(max_length=10, unique=True, blank=False, null=False)
    nombres = models.CharField(max_length=30, blank=False, null=False)
    apellidos = models.CharField(max_length=30, blank=False, null=False)
    serial_patria = models.IntegerField(blank=True, null=True)
    codigo_patria = models.IntegerField(blank=True, null=True)
    telefono = models.CharField(max_length=12, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    direccion = models.TextField(max_length=255, blank=False, null=False)

    def __str__(self):
        return f"{self.nombres} {self.apellidos} - C.I: {self.cedula}"

# creando DB de Alumnos
class Alumno(models.Model):
    nombres = models.CharField(max_length=30, blank=False, null=False)
    apellidos = models.CharField(max_length=30, blank=False, null=False)
    edad = models.IntegerField(blank=False, null=False)
    sexo = models.CharField(max_length=9, blank=False, null=False)
    grado_y_seccion = models.CharField(max_length=12, blank=False, null=False)
    fecha_de_nacimiento = models.DateField(blank=False, null=False)
    lugar_de_nacimiento = models.TextField(max_length=255, blank=False, null=False)
    # para asociar cada uno de los alumnos con el representante
    representante = models.ForeignKey(Representante, on_delete=models.CASCADE, related_name='alumno')

    def __str__(self):
        return f"{self.nombres} {self.apellidos} - Grado/sección: {self.grado_y_seccion}"

# creando DB de eliminados
class RegistroEliminado(models.Model):
    tipo = models.CharField(max_length=20)  # 'representante' o 'alumno'
    datos = models.JSONField()
    eliminado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    fecha_eliminacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.tipo} eliminado el {self.fecha_eliminacion}"

templates/representante/create.html
{% extends "layout/base.html" %}

{% block 'title' %} Añadir Representante {{ representante }} {% endblock  %}

{% block 'styles' %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/form.css" %}">
{% endblock  %}

{% block 'content' %}
    <div class="container">
        {% include "representante/partials/msg_success.html" %}

        <span class='btn-aux'>
            <a href="{% url "representante" %}" class='btn btn-detail'>Volver atrás</a>
        </span>

        {# el method='PUT' se usa para actualizar pero aqui usamos el post #}
        <form action="{% url "representante_create" %}" method='POST'>
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Guardar">
        </form>
    </div>
{% endblock  %}

templates/representante/detail.html
{% extends "layout/base.html" %}

{% block 'title' %} Representante {{ representante }} {% endblock  %}

{% block 'content' %}
    <div class="container">
        <span class='btn-aux'>
            <a href="{% url "representante" %}" class='btn btn-detail'>Volver atrás</a>
        </span>

        <table>
            <tr>
                <th>Cédula:</th>
                <td>{{representante.cedula}}</td>
            </tr>
            <tr>
                <th>Nombres:</th>
                <td>{{representante.nombres}}</td>
            </tr>
            <tr>
                <th>Apellidos:</th>
                <td>{{representante.apellidos}}</td>
            </tr>
            <tr>
                <th>Serial Patria:</th>
                <td>{{representante.serial_patria}}</td>
            </tr>
            <tr>
                <th>Código Patria:</th>
                <td>{{representante.codigo_patria}}</td>
            </tr>
            <tr>
                <th>Teléfono:</th>
                <td>{{representante.telefono}}</td>
            </tr>
            <tr>
                <th>Email:</th>
                <td>{{representante.email}}</td>
            </tr>
            <tr>
                <th>Dirección:</th>
                <td>{{representante.direccion}}</td>
            </tr>
        </table>
        <br>

        <h2>Representante de</h2>
        <ul class='alumnos'>
            {% for alumno in alumnos %}
                <li>{{ alumno}}</li>
            {% empty %}
                <li>No hay alumnos asociados a este representante.</li>
            {% endfor %}
        </ul>
    </div>
{% endblock  %}

templates/representante/edit.html
{% extends "layout/base.html" %}

{% block 'title' %} Editar Representante {{ representante }} {% endblock  %}

{% block 'styles' %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/form.css" %}">
{% endblock  %}

{% block 'content' %}
    <div class="container">
        {% include "representante/partials/msg_success.html" %}

        <span class='btn-aux'>
            <a href="{% url "representante" %}" class='btn btn-detail'>Volver atrás</a>
        </span>

        {# el method='PUT' se usa para actualizar pero aqui usamos el post #}
        <form action="{% url "representante_edit" id=id %}" method='POST'>
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Guardar">
        </form>
    </div>
{% endblock  %}

templates/representante/index.html
{% extends "layout/base.html" %}

{% block 'title' %} Representantes {% endblock  %}

{% block 'content' %}
    <div class="container">
        {#para visulizar el mensaje #}
        {% include "representante/partials/msg_delete.html" %}

        <h1>Gestor de Representantes</h1>

        {% include "representante/partials/search.html" %}
        {% include "representante/partials/by_initial.html" %}

        <span class='btn-aux'>
            <a href="{% url "representante" %}" class='btn btn-detail'>Ver todos</a>
            {% if perms.repreStudy.add_representante %}
                <a href="{% url "representante_create" %}" class='btn btn-edit'>Añadir</a>
            {% else %}
                <a href="javascript:void(0);" class='btn btn-edit btn-disabled' title="No tienes permiso para añadir">Añadir</a>
            {% endif %}
        </span>

        {% include "representante/partials/lista_representante.html" %}
    </div>
{% endblock  %}

templates/representante/representante_confirm_delete.html
{% extends "layout/base.html" %}

{% block 'title' %} Eliminar {{ representante }} {% endblock  %}

{% block 'content' %}
    <div class="container">
        <h1>¿Estás seguro de borrar el representante?</h1>
        <br>

        <table>
            <tr>
                <th>Cédula:</th>
                <td>{{representante.cedula}}</td>
            </tr>
            <tr>
                <th>Nombres:</th>
                <td>{{representante.nombres}}</td>
            </tr>
            <tr>
                <th>Apellidos:</th>
                <td>{{representante.apellidos}}</td>
            </tr>
            <tr>
                <th>Serial Patria:</th>
                <td>{{representante.serial_patria}}</td>
            </tr>
            <tr>
                <th>Código Patria:</th>
                <td>{{representante.codigo_patria}}</td>
            </tr>
            <tr>
                <th>Teléfono:</th>
                <td>{{representante.telefono}}</td>
            </tr>
            <tr>
                <th>Email:</th>
                <td>{{representante.email}}</td>
            </tr>
            <tr>
                <th>Dirección:</th>
                <td>{{representante.direccion}}</td>
            </tr>
        </table>

        <br>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="confir-delete affirmative" value="Sí, borrar">
            <a href="{% url 'representante' %}" class="confir-delete denied">No, cancelar</a>
        </form>
    </div>
{% endblock %}