register_rest/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('repreStudy/', include('repreStudy.urls')),
    path('', views.index , name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

repreStudy/urls.py
from django.urls import path, include

urlpatterns = [
    path('login/', include('repreStudy.login_urls')),
    path('representante/', include('repreStudy.representante_urls')),
    path('alumno/', include('repreStudy.alumno_urls')),
]

repreStudy/models.py
from django.db import models
from django.contrib.auth.models import User


# creando DB de representantes
class Representante(models.Model):
    cedula = models.CharField(max_length=10, unique=True, blank=False, null=False)
    nombres = models.CharField(max_length=30, blank=False, null=False)
    apellidos = models.CharField(max_length=30, blank=False, null=False)
    serial_patria = models.IntegerField(blank=True, null=True)
    codigo_patria = models.IntegerField(blank=True, null=True)
    telefono = models.CharField(max_length=12, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    direccion = models.TextField(max_length=255, blank=False, null=False)

    def __str__(self):
        return f"{self.nombres} {self.apellidos} - C.I: {self.cedula}"

# creando DB de Alumnos
class Alumno(models.Model):
    nombres = models.CharField(max_length=30, blank=False, null=False)
    apellidos = models.CharField(max_length=30, blank=False, null=False)
    edad = models.IntegerField(blank=False, null=False)
    sexo = models.CharField(max_length=9, blank=False, null=False)
    grado_y_seccion = models.CharField(max_length=12, blank=False, null=False)
    fecha_de_nacimiento = models.DateField(blank=False, null=False)
    lugar_de_nacimiento = models.TextField(max_length=255, blank=False, null=False)
    # para asociar cada uno de los alumnos con el representante
    representante = models.ForeignKey(Representante, on_delete=models.CASCADE, related_name='alumno')

    def __str__(self):
        return f"{self.nombres} {self.apellidos} - Grado/sección: {self.grado_y_seccion}"

# creando DB de eliminados
class RegistroEliminado(models.Model):
    tipo = models.CharField(max_length=20)  # 'representante' o 'alumno'
    datos = models.JSONField()
    eliminado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    fecha_eliminacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.tipo} eliminado el {self.fecha_eliminacion}"

templates/representante/partials/by_initial.html
<div class='letters' id='letters'>
    <a href="{% url "representante" letter='A' %}">A</a>
    <a href="{% url "representante" letter='B' %}">B</a>
    <a href="{% url "representante" letter='C' %}">C</a>
    <a href="{% url "representante" letter='D' %}">D</a>
    <a href="{% url "representante" letter='E' %}">E</a>
    <a href="{% url "representante" letter='F' %}">F</a>
    <a href="{% url "representante" letter='G' %}">G</a>
    <a href="{% url "representante" letter='H' %}">H</a>
    <a href="{% url "representante" letter='I' %}">I</a>
    <a href="{% url "representante" letter='J' %}">J</a>
    <a href="{% url "representante" letter='K' %}">K</a>
    <a href="{% url "representante" letter='L' %}">L</a>
    <a href="{% url "representante" letter='M' %}">M</a>
    <a href="{% url "representante" letter='N' %}">N</a>
    <a href="{% url "representante" letter='Ñ' %}">Ñ</a>
    <a href="{% url "representante" letter='O' %}">O</a>
    <a href="{% url "representante" letter='P' %}">P</a>
    <a href="{% url "representante" letter='Q' %}">Q</a>
    <a href="{% url "representante" letter='R' %}">R</a>
    <a href="{% url "representante" letter='S' %}">S</a>
    <a href="{% url "representante" letter='T' %}">T</a>
    <a href="{% url "representante" letter='U' %}">U</a>
    <a href="{% url "representante" letter='V' %}">V</a>
    <a href="{% url "representante" letter='W' %}">W</a>
    <a href="{% url "representante" letter='X' %}">X</a>
    <a href="{% url "representante" letter='Y' %}">Y</a>
    <a href="{% url "representante" letter='Z' %}">Z</a>
</div>

templates/representante/partials/lista_representante.html
<ul class='list'>
    {% for representante in representantes %}
    <li>
        {{representante.nombres}}
        <span>
            <a href="{% url "representante_view" id=representante.id  %}" class='btn btn-detail'>Ver</a>

            {% if perms.repreStudy.change_representante %}
                <a href="{% url "representante_edit" id=representante.id  %}" class='btn btn-edit'>Editar</a>
            {% else %}
                <a href="javascript:void(0);" class='btn btn-edit btn-disabled' title="No tienes permiso para editar">Editar</a>
            {% endif %}

            {% if perms.repreStudy.delete_representante %}
                <a href="{% url "representante_delete" id=representante.id  %}" class='btn btn-delete'>Borrar</a>
            {% else %}
                <a href="javascript:void(0);" class='btn btn-delete btn-disabled' title="No tienes permiso para borrar">Borrar</a>
            {% endif %}
        </span>
    </li>
    {% endfor %}

    {# para visulizar el mensaje de no encontrado #}
    {% if no_results_message %}
        <li>{{ no_results_message }}</li>
    {% endif %}

    {# para visualizar la paginación #}
    <div class="pagination">
        <span class="step-links">
            {% if representantes.has_previous %}
                <a href="?page=1">Primera</a>
                <a href="?page={{ representantes.previous_page_number }}&search={{ search_query }}">Anterior</a>
            {% endif %}
    
            <span class="current">
                Página {{ representantes.number }} de {{ representantes.paginator.num_pages }}
            </span>
    
            {% if representantes.has_next %}
                <a href="?page={{ representantes.next_page_number }}&search={{ search_query }}">Siguiente</a>
                <a href="?page={{ representantes.paginator.num_pages }}&search={{ search_query }}">Última</a>
            {% endif %}
        </span>
    </div>
    
</ul>

templates/representante/partials/msg_delete.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="alert-delete"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/representante/partials/msg_success.html
{#para visulizar el mensaje #}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert-success"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/representante/partials/search.html
<form class='search' action="{% url "representante" %}" method='GET'>
    <input type="text" name="search" placeholder='Buscar representante...'>
    <button type="submit" class='btn btn-detail'>Buscar</button>
</form>