register_rest/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('repreStudy/', include('repreStudy.urls')),
    path('', views.index , name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

repreStudy/urls.py
from django.urls import path, include

urlpatterns = [
    path('login/', include('repreStudy.login_urls')),
    path('representante/', include('repreStudy.representante_urls')),
    path('alumno/', include('repreStudy.alumno_urls')),
]

repreStudy/models.py
from django.db import models
from django.contrib.auth.models import User


# creando DB de representantes
class Representante(models.Model):
    cedula = models.CharField(max_length=10, unique=True, blank=False, null=False)
    nombres = models.CharField(max_length=30, blank=False, null=False)
    apellidos = models.CharField(max_length=30, blank=False, null=False)
    serial_patria = models.IntegerField(blank=True, null=True)
    codigo_patria = models.IntegerField(blank=True, null=True)
    telefono = models.CharField(max_length=12, blank=False, null=False)
    email = models.EmailField(blank=False, null=False)
    direccion = models.TextField(max_length=255, blank=False, null=False)

    def __str__(self):
        return f"{self.nombres} {self.apellidos} - C.I: {self.cedula}"

# creando DB de Alumnos
class Alumno(models.Model):
    nombres = models.CharField(max_length=30, blank=False, null=False)
    apellidos = models.CharField(max_length=30, blank=False, null=False)
    edad = models.IntegerField(blank=False, null=False)
    sexo = models.CharField(max_length=9, blank=False, null=False)
    grado_y_seccion = models.CharField(max_length=12, blank=False, null=False)
    fecha_de_nacimiento = models.DateField(blank=False, null=False)
    lugar_de_nacimiento = models.TextField(max_length=255, blank=False, null=False)
    # para asociar cada uno de los alumnos con el representante
    representante = models.ForeignKey(Representante, on_delete=models.CASCADE, related_name='alumno')

    def __str__(self):
        return f"{self.nombres} {self.apellidos} - Grado/sección: {self.grado_y_seccion}"

# creando DB de eliminados
class RegistroEliminado(models.Model):
    tipo = models.CharField(max_length=20)  # 'representante' o 'alumno'
    datos = models.JSONField()
    eliminado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    fecha_eliminacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.tipo} eliminado el {self.fecha_eliminacion}"

templates/alumno/alumno_confirm_delete.html
{% extends "layout/base.html" %}

{% block 'title' %} Eliminar {{ alumno }} {% endblock  %}

{% block 'content' %}
    <div class="container">
        <h1>¿Estás seguro de borrar el alumno?</h1>
        <br>

        <table>
            <tr>
                <th>Nombres:</th>
                <td>{{alumno.nombres}}</td>
            </tr>
            <tr>
                <th>Apellidos:</th>
                <td>{{alumno.apellidos}}</td>
            </tr>
            <tr>
                <th>Edad:</th>
                <td>{{alumno.edad}}</td>
            </tr>
            <tr>
                <th>Sexo:</th>
                <td>{{alumno.sexo}}</td>
            </tr>
            <tr>
                <th>Grado y Sección:</th>
                <td>{{alumno.grado_y_seccion}}</td>
            </tr>
            <tr>
                <th>Fecha de nacimiento:</th>
                <td>{{alumno.fecha_de_nacimiento}}</td>
            </tr>
            <tr>
                <th>Lugar de nacimiento:</th>
                <td>{{alumno.lugar_de_nacimiento}}</td>
            </tr>
            <tr>
                <th>Representante:</th>
                <td>{{alumno.representante}}</td>
            </tr>
        </table>
        <br>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="confir-delete affirmative" value="Sí, borrar">
            <a href="{% url 'alumno' %}" class="confir-delete denied">No, cancelar</a>
        </form>
    </div>
{% endblock %}

templates/alumno/create.html
{% extends "layout/base.html" %}

{% block 'title' %} Añadir alumno {{ alumno }} {% endblock  %}

{% block 'styles' %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/form.css" %}">
{% endblock  %}

{% block 'content' %}
    <div class="container">
        {% include "alumno/partials/msg_success.html" %}

        <span class='btn-aux'>
            <a href="{% url "alumno" %}" class='btn btn-detail'>Volver atrás</a>
        </span>

        {# el method='PUT' se usa para actualizar pero aqui usamos el post #}
        <form action="{% url "alumno_create" %}" method='POST'>
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Guardar">
        </form>
    </div>
{% endblock  %}

templates/alumno/detail.html
{% extends "layout/base.html" %}

{% block 'title' %} alumno {{ alumno }} {% endblock  %}

{% block 'content' %}
    <div class="container">

        <span class='btn-aux'>
            <a href="{% url "alumno" %}" class='btn btn-detail'>Volver atrás</a>
        </span>

        <table>
            <tr>
                <th>Nombres:</th>
                <td>{{alumno.nombres}}</td>
            </tr>
            <tr>
                <th>Apellidos:</th>
                <td>{{alumno.apellidos}}</td>
            </tr>
            <tr>
                <th>Edad:</th>
                <td>{{alumno.edad}}</td>
            </tr>
            <tr>
                <th>Sexo:</th>
                <td>{{alumno.sexo}}</td>
            </tr>
            <tr>
                <th>Grado y Sección:</th>
                <td>{{alumno.grado_y_seccion}}</td>
            </tr>
            <tr>
                <th>Fecha de nacimiento:</th>
                <td>{{alumno.fecha_de_nacimiento}}</td>
            </tr>
            <tr>
                <th>Lugar de nacimiento:</th>
                <td>{{alumno.lugar_de_nacimiento}}</td>
            </tr>
            <tr>
                <th>Representante:</th>
                <td>{{alumno.representante}}</td>
            </tr>
        </table>
    </div>
{% endblock  %}

templates/alumno/edit.html
{% extends "layout/base.html" %}

{% block 'title' %} Editar alumno {{ alumno }} {% endblock  %}

{% block 'styles' %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/form.css" %}">
{% endblock  %}

{% block 'content' %}
    <div class="container">
        {% include "alumno/partials/msg_success.html" %}

        <span class='btn-aux'>
            <a href="{% url "alumno" %}" class='btn btn-detail'>Volver atrás</a>
        </span>

        {# el method='PUT' se usa para actualizar pero aqui usamos el post #}
        <form action="{% url "alumno_edit" id=id %}" method='POST'>
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Guardar">
        </form>
    </div>    
{% endblock  %}

templates/alumno/index.html
{% extends "layout/base.html" %}

{% block 'title' %} Alumnos {% endblock  %}

{% block 'content' %}
    <div class="container">
        {#para visulizar el mensaje #}
        {% include "alumno/partials/msg_delete.html" %}

        <h1>Gestor de alumnos</h1>

        {% include "alumno/partials/search.html" %}
        {% include "alumno/partials/by_initial.html" %}

        <span class='btn-aux'>
            <a href="{% url "alumno" %}" class='btn btn-detail'>Ver todos</a>
            {% if perms.repreStudy.add_alumno %}
                <a href="{% url "alumno_create" %}" class='btn btn-edit'>Añadir</a>
            {% else %}
                <a href="javascript:void(0);" class='btn btn-edit btn-disabled' title="No tienes permiso para añadir">Añadir</a>
            {% endif %}
        </span>

        {% include "alumno/partials/lista_alumno.html" %}
    </div>
{% endblock  %}